using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class ChestBehavior : MonoBehaviour
{
    // Reference to the player's animator
    public Animator anim;


    // Start is called before the first frame update
    void Start()
    {
           anim = gameObject.GetComponent<Animator>();
    
    }

    private void OnTriggerEnter(Collider other)
    {
        if (other.CompareTag("Player"))
        {
            anim.SetBool("isOpen", true);
        }

    }

    private void OnTriggerExit(Collider other)
    {
        if (other.CompareTag("Player"))
        {
            anim.SetBool("isOpen", false);
        }
    }

    //Chest animation event handler
    public void ChestEvt()
    {
        Debug.Log("The chest has Opened!");
    }
}
